### ISSUE TITLE
Constant propagation

### ISSUE THREAD

**Issue by aj3189** [PrincetonUniversity/lucid#27]
Probably a big project with a few levels, but there should be as much constant propagation as possible due to hardware constraints. This comes up a lot with polymorphic sizes, other compilation passes. Ideas:

- simple constant prop (adding of two constants/bitshifts with constant size/etc.)
- Eliminating branches of match tables/if statements if they switch on a constant

**Comment by DKLoehr** [comment]
We do both these things in the midend transformation that we call [Partial Interpretation](https://github.com/PrincetonUniversity/lucid/blob/main/src/lib/midend/transformations/PartialInterpretation.ml), along with a few other optimizations. Is there somewhere you see an easy optimization that isn’t happening?

**Comment by aj3189** [comment]
Maybe I made this in error... John mentioned this might happen in the partial interpretation step. I think I am just not up to date. I think I will close.
